version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: remindz_postgres
    restart: always
    environment:
      POSTGRES_USER: remindz
      POSTGRES_PASSWORD: remindz
      POSTGRES_DB: remindz
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:7
    container_name: remindz_redis
    ports:
      - "6379:6379"

volumes:
  pgdata:
